# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60c454b219b2e08b1843b50e5d65fb27783d297c9590740de651ba4d3573c9834d9e2093c59d52442ec02548a9004965c069e2d2cb27ad9801be15519c3bcd39

test:
  secret_key_base: d5455f5284da33b74417689e3a0298edf98e8348914bf2ae23b3aa49b20576a2748e7d78fa0f3ec9bc785269dad395c99ad4f80b1d6a28bfc922926510d0eb0f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
